const users = [
    { uname: "user1", psw: "password123" },
    { uname: "user2", psw: "password456" },
    { uname: "user3", psw: "password789" },
];


const informations = [
    { title: "Darslik ma'lumotlari davrlar oraligida", data: "Qolingizdagi Ozbekiston tarixi darsligi XIX asrning ikkinchi yarmi va XX asrning 90-yillariga qadar sodir bolgan voqealarni oz ichiga oladi. Bu davr Vatanimiz tarixining eng murakkab va ziddiyatli yillaridir. ", },
    { title: "Darslikda nimalar yoritilgan", data: "Mazkur darslik Vatanimiz tarixida yoqotishlar va talafotlarga tola bolgan, shuningdek, ota-bobolarimizning yurt ozodligi va mustaqilligi uchun olib borgan qahramonona kurashlari hamda ozbek xalqining bunyodkorlik faoliyati va fidokorona mehnatlarini oz ichiga olgan davrlar haqida hikoya qiladi. ", },
    { title: "Tarix saboqlari", data: "Tarix saboqlari bugungi kunda ham bizni hushyorlikka undaydi. Ilmsizlik, yangilikka intilmaslik, jahon hamjamiyatidan uzilib qolishning oqibatlari tarixiy misollar orqali yoritilgan. Shu ma'noda bugungi kunda mamlakatimizda davlatning ustuvor yonalishlaridan biri talim sohasini rivojlantirishdir" },
    { title: "Abdurauf Fitrat <<Tarix...>>", data: "«Tarix millatlarning otmishi, taraqqiyoti hamda tanazzulining sabablarini organaturgon ilmdir». \n Abdurauf Fitrat" },
    { title: "1712", data: "1712 - yilda Tomas Nyukomen bug mashinasini ixtiro qildi. " },
    { title: "1860", data: "1860 - yillarda fransuz olimi Lui Paster tomonidan pasterizatsiya usuli kashf etildi" },
    { title: "Mendeleyev 1869", data: "1869 - yilda rus kimyogari Dmitriy Mendeleyev kimyoviy elementlarning davriy jadvalini tuzib chiqdi." },
    { title: "1879 Tomas Edison", data: "1879 - yilda ixtirochi Tomas Edison (1847 - 1931) hozirda biz ishlatadigan xojalik lampochkasini ixtiro qildi. Uning ixtirosiga Svanning tajribalari asos bolib, Tomas uni yanada takomillashtirdi." },
    { title: "Sovutgich Linde", data: "Karl fon Linde 1900 - yilda ixtiro qilgan Linde sovutgichi." },
    { title: "Alixonto‘ra Sog‘uniy «Turkiston qayg‘usi».", data: "«...Yoshlikdan ilmni qunt bilan organish lozimligini aytib, «Yoshlikda egallangan bilim toshga oyilgan naqshdur», «Ong yoq joyda jasorat bolmaydi», «Bu dunyoda hech narsa tan sogliqqa yetmas» kabi shiorlarni kop eshitar edik. Milliy tarix darslaridan birida shunday deganlar: «Insonlar oz hayotlarini ongli ravishda tushunib turishlari uchun dunyo ilmlari ichida boshqalardan kora tarix ilmiga hojatlari ayniqsa kopdur. Shuning uchun har davrning dono olimlari tarafidan bu togrida bek (kop) kitoblar yozilmish ekandur. Tarix demak, oquvchilarning koz oldilariga qoyilgan bir kozgu kabi bolib, unga qaragan kishilar esa yuz - kozlariga yuqqan yomon narsalarni korar ekanlar, albatta, undan ozlarini tozalaydilar. Shunga oxshash, otmishdagi ota-bobolarning oynaklarini keyingi bolalari qollariga olib qarasalar, o‘zlarining kim ekanliklarini, endi kim bolgonliklarini shu kozguda ochiq koradilar. Mehribon ona Vatanlari bosqinchi oyoqlar ostida depsalib, ingrab yotqonligini korgach, uning sabablarini tekshirishga kirishadilar. Ongsizlik olim uyqusida yotgan bir millatni uygotish uchun otmishdagi ota - bobolarining shonlik tarixini bilishdan ortiq narsa yoqdir. Bu ilmdan kutilgan asosiy maqsadlar bir davlat qurilgandan songra, u qaysi ishlar bilan taraqqiy topib rivojlanmishdur, yoki inqirozga uchrab zavol topishi nima sababdan bolishidur. Chunki, dunyoda otgan, yo otmoqda bolgan yaxshi - yomon ishlar paydo bolishining, albatta, sabablari bordur. Hayot olamida hech narsa sababsiz yuzaga chiqishi mumkin emasdur...»    Alixontora Soguniy «Turkiston qaygusi»." },
    { title: "Buxoro amirligi va chegaralari", data: "Buxoro amirligi chegaralari janubda Amudaryoning chap qirgogidan boshlanib shimolda Sirdaryogacha, sharqda Pomir toglaridan garbda Xiva xonligi yerlarigacha chozilgan. Davlat hududi XIX asrning ortalarida Eron, Afgoniston, Qoqon va Xiva xonliklari, qozoq juzlari yerlari bilan chegaradosh bolgan. Buxoro amirligining aholisi soni 2 million atrofida bo‘lgan." },
    { title: "Buxoro amirligi", data: "Buxoro amirligining markaziy qismi Buxoro va Samarqand shaharlari joylashgan Zarafshon vodiysi hisoblangan. Shu bilan birga hududiy jihatdan viloyat va tumanlarga bolinib, ularni amir tomonidan tayinlangan beklar boshqargan. Amirlik tarkibida 40 ta viloyat bolgan. " },
    { title: "Xiva xonligi, umumiy ma'lumotlar", data: "Xiva xonligi XIX asrning ikkinchi yarmida janubda Eron, sharqda Buxoro amirligi, garbda Kaspiy dengizi, shimolda qozoq juzlari yerlari bilan chegaradosh bolgan. Xonlikning mamuriy markazi Xiva shahri hisoblangan. Xiva xonligida Xiva, Kat, Yangi Urganch, Hazorasp, Qongirot, Xojayli kabi bekliklarning markazlari bor edi. Xiva xonligi 18 ta beklik, 2 ta noiblikka bolingan va ularni xon tomonidan tayinlangan beklar va toralar boshqargan." },
    { title: "Xiva aholisi", data: "XIX asrning ikkinchi yarmida Xiva xonligida aholi soni 800 ming kishidan ortiq bolib, asosan ozbeklardan tashkil topgan. " },
    { title: "Qo'qon xonligi umumiy ma'lumotlar", data: "Qoqon xonligi. XVIII asrning boshlarida Buxoro amirligidan Fargona vodiysi va Sirdaryoning quyi qismigacha bolgan hududlar ajrab, mustaqil davlat - Qoqon xonligi tashkil topadi. Xonlik sharqda Sharqiy Turkiston, garbda Buxoro amirligi va Xiva xonligi, shimolda Qozoq juzlari yerlari bilan chegaradosh bolgan. Xonlikning janubiy chegaralari Qorategin, Kolob, Darvoz, Shognon singari togli olkalarni oz ichiga olib, bu hududlar uchun Buxoro amirligi bilan tez-tez toqnashuvlar bolib turgan. Xonlikning hududi Buxoro amirligi va Xiva xonliklaridan farqli olaroq, sersuv daryolar, solim vodiylar, serhosil yerlarga boy bolgan. Qoqon xonligida aholi soni 3 millionga yaqin bolgan. " },
    { title: "Qo'qon xonligi aholisi", data: "Qoqon xonligi 15 ta beklikka bolinib, ularni, asosan, xonning qarindoshlari va yaqinlari orasidan tayinlangan kishilar boshqargan." },
    { title: "Xonliklar etnik tarkiblari", data: "XIX asrning ortalariga kelib, Buxoro amirligi, Xiva va Qoqon xonliklari aholisining etnik tarkibi bir-biriga yaqin, asosan, ozbeklardan iborat bolgan. Shu bilan birga uchala xonlik hududlarida tojiklar, qozoqlar, qoraqalpoqlar, turkmanlar, qirgizlar bilan birga uygurlar, yahudiylar, hindlar va boshqa elat vakillari ham yashagan." },
    { title: "Buxoro amirligida mansablar", data: "Buxoro amirligida oliy hukmdor amir hisoblanib, uning hokimiyati avloddan avlodga meros tarzida otgan. Amirlikni cheklanmagan hokimiyatga ega bolgan mangitlar sulolasiga mansub hukmdorlar boshqargan. Buxoro shahri amirlikning mamuriy markazi edi. Amirlikda ijro hokimiyati bosh vazir - qoshbegi qolida bolgan. Viloyat va tuman beklari qoshbegi tavsiyasi bilan tayinlangan. Moliya va xazina ishlari, soliqlar toplanishi kabi sohalarni devonbegi idora qilgan. Devonbegiga tashqi aloqalarni yuritish ham yuklatilgan. Unga amirlik hujjatlarini yuritishga masul mirzaboshi boysungan. Amirlikda soliqlarni oz vaqtida yigishga javobgar kishi mushrif hisoblangan. Dodxoh lavozimini egallab turgan shaxs xalqning shikoyatlari bilan shugullangan. Oliy hukmdor farmonlarini parvonachi elon qilgan. Shariat qoidalari va qonunlar ijrosi, sud ishlarini nazorat qilishni shayxulislom bajargan. Amir qarorgohi hisoblangan arkda taxt vorisi - valiahd tarbiyasi bilan otaliq mashgul bolgan. Topchiboshi amir qoshinlarining bosh qomondoni bolgan. Amirlikning shaharlarida tinchlik va tartibni saqlashga amir soqchilari boshligi - mirshabboshi masul hisoblangan. Kokaldosh mamlakat xavfsizligi, amirning yaqinlari, dostlari va dushmanlari togrisida malumotlar toplash bilan shugullangan." },
    { title: "Xiva xonligida mansablar", data: "Xiva xonligi qongirotlar sulolasi tomonidan boshqarilib, uning oliy hukmdori xon hisoblangan. Xon qarorgohi Xiva shahrida joylashgan. Bu shaharda ichki - Ichan qala va mudofaa devori bilan oralgan tashqi - Dishan qala mavjud bolgan. Xonlikda oliy amaldor devonbegi hisoblanib, uning ixtiyorida qoshbegi, mehtar, otaliqdan iborat kengash faoliyat korsatgan. Aholining tinchligi va osoyishtaligi bilan mirshabboshi, xonlikdagi tartib-intizom ishlariga xon qoshinlarining bosh qomondoni - yasovulboshi, diniy ishlar va shariat qoidalariga rioya etilishi va amal qilinishi masalalariga shayxulislom, sugorish inshootlari va suv taminoti hamda taqsimotiga mirobboshi masul hisoblangan. Harbiy bolinmalarga lashkarboshilar qomondonlik qilgan. Askarlik xizmatida bolganlar soliqlardan ozod qilingan." },
    { title: "Qo'qon xonligida mansablar", data: "Qo‘qon xonligi minglar sulolasi tomonidan boshqarilgan va uning mamuriy markazi Qoqon shahri bolgan. Eng yuqori harbiy lavozim amirlashkar bolib, u harbiy vazir hisoblangan. Xonlikdagi alohida harbiy bolinmalarga mingboshilar rahbarlik qilgan. Ular bosh vazir vazifasini ham bajargan. Xazina ishlari va xarajatlarini mehtar nazorat qilib borgan. Qozikalon, qozilar islom dini qoidalari asosida sud ishlarini olib borganlar. Muhtasib raislar diniy ishlar, shariat qoidalariga rioya qilinishi, savdo-sotiqning togri yuritilishini nazorat qilganlar. Xonlikdagi ichki tartib-intizom ishlari bilan mirshablar shugullangan." },
    { title: "Solg'ut - Xivaning asosiy solig'i", data: "Xiva xonligida asosiy soliq solgut deb atalgan." },
    { title: "Xonlik va amirlikda yerga egalik qilish", data: "Buxoro amirligi, Xiva va Qoqon xonliklarida yerga egalik qilish shakllari deyarli bir xil edi. XIX asrda aholining aksariyati katta yer egalariga tegishli ekin maydonlarida mehnat qilganlar. Ular ijaraga olgan yerlari uchun hosilning bir qismini xiroj sifatida tolaganlar. Soliq va tolovlar mahsulot yoki pul korinishida tolangan. Bundan tashqari sugorish inshootlari, yollar, kopriklar qurish va ularni tamirlash kabi ishlar ham bolgan. Bu davrda aholidan xiroj, zakot, suv, tegirmon, tuz, mulk, tomorqa, bog va boshqa soliqlar yigilgan. Xiva xonligida asosiy soliq solgut deb atalgan. Harbiy majburiyatda har bir erkak kishi oziq-ovqati, qurol-aslahasi bilan birga qatnashishi kerak bolgan. Har bir hududda aholi va mamuriyat vakillari sugorish sohasiga masul va javobgar bolgan. Sugorish ishlari bilan miroblar shugullanganlar. Qoqon xonligida aholi, asosan, sugorma dehqonchilik bilan shugullangan. Vodiy hududida yirik sugorish inshootlari - Shahrixonsoy, Andijonsoy, Margilonsoy, Yangiariq, Ulugnor, Qoradaryo kabilar bolgan. Suv chiqishi qiyin bolgan joylarga maxsus qurilmalar - chigirlar yordamida suv chiqarilgan. Amudaryo, Sirdaryo suvlari turli suniy sugorish tizimlari - kanallar hamda uning boylariga qurilgan togonlar orqali ekin maydonlariga yetkazilgan." },
    { title: "Agrar so'zi", data: "Agrar (lotincha - agrarius) - yerga, dalaga oid - qishloq xojaligi bilan shugullaniladigan hududga, aholining qishloq xojaligi mahsulotlari yetishtirish hajmi ustun bolgan joyga nisbatan qollaniladi." },
    { title: "Orta Osiyoda hunarmandchilik markazlari", data: "Orta Osiyo davlatlarida koplab hunarmandchilik markazlari mavjud bolib, ular mahalliy xususiyatlariga kora turli sohalarga ixtisoslashgan." },
    { title: "Margilonda hunarmandchilik", data: "Margilonda atlas toqish va doppichichilik rivojlangan." },
    { title: "Rishtonda hunarmandchilik", data: "Rishtonda kulolchilik rivojlangan." },
    { title: "Shahrixonda hunarmandchilik", data: "Shahrixonda pichoqchilik, doppichichilik va duradgorlik rivojlangan." },
    { title: "Chustda hunarmandchilik", data: "Chustda doppichichilik va pichoqchilik rivojlangan." },
    { title: "Qoqonda hunarmandchilik", data: "Qoqonda temirchilik, duradgorlik va zargarlik rivojlangan." },
    { title: "Buxoro va Samarqandda hunarmandchilik", data: "Buxoro va Samarqandda zargarlik rivojlangan." },
    { title: "Xivada hunarmandchilik", data: "Xivada memorchilik va ganchkorlik rivojlangan." },
    { title: "Buxoro amirligidagi hunarmandchilik", data: "Buxoro amirligida kulolchilik, temirchilik, misgarlik, zardozlik, shishasozlik, kandakorlik va badiiy kashtachilik sohalari keng tarqalgan." },
    { title: "Xonliklarda temirchilik sohasi", data: "Xonliklarda temir mahsulotlariga ehtiyoj katta bolgani uchun metallga ishlov beruvchi mahalliy temirchilik sohasi rivojlangan." },
    { title: "Orta Osiyo savdogarlarining savdo aloqalari", data: "Orta Osiyo savdogarlari Eron, Xitoy, Hindiston, Afgoniston, Rossiya davlatlari va qozoq juzlari bilan savdo-sotiq qilganlar." },
    { title: "Hunarmandlar mahsulotlarining xorijdagi bahosi", data: "Xorijda hunarmandlarning zargarlik mahsulotlari, shoyi va atlas matolari, kulolchilik buyumlari yuqori baholangan." },
    { title: "Fuqarolar urushi", data: "Bu davrda AQSHda Shimol va Janub ortasida boshlangan fuqarolar urushi (1861 - 1865) tufayli Rossiyaning toqimachilik sanoati uchun paxta xomashyosi taqchilligi vujudga keldi." },
    { title: "To‘qimachilik sanoati", data: "Toqimachilik sanoati uchun xomashyo bolgan paxtaning yetishmasligi Orta Osiyo yerlari va resurslariga ehtiyojni yanada oshirdi." },
    { title: "Ta'lim tizimi", data: "Har uchala xonlikda talim tizimi deyarli bir xilda bolgan." },
    { title: "O‘qish muddati", data: "Madrasalarda oqish muddati asosan sentyabr oyining ikkinchi yarimida boshlanib, mart oyining oxiriga qadar davom etgan." },
    { title: "Oqish mavsumi", data: "Oqish mavsumi kopincha 6 oy bolgan." },
    { title: "Ta’lim muddati", data: "Talim olish muddati kop hollarda cheklanmagan." },
    { title: "Mutaxassislar tayyorlash", data: "Madrasalar mudarris, imom, qozi, mirza, moliyaviy ishlarni olib boruvchi, yer-suvni taqsimlovchi singari mutaxassislarni tayyorlagan." },
    { title: "Ijod tili", data: "Bu davrda ikki tilda, yani ozbek va fors tillarida ijod qilingan." },
    { title: "Marifatga intilish", data: "Mahalliy aholi marifatga intilib kelgan." },
    { title: "Maktablar", data: "Ananaviy talim tizimida maktablar boshlangich oquv maskanlari bolib, ular shahar, qishloqlarda va ovullarda ham mavjud edi." },
    { title: "Maktab tashkiloti", data: "Ular odatda, masjid, madrasa huzurida yoki xususiy hovlilarda tashkil etilgan." },
    { title: "Darslar", data: "Maktablarda diniy bilimlar bilan bir qatorda jogrofiya, sanoq, savodxonlik kabi darslar ham berilgan." },
    { title: "Ichki hovlilar", data: "Har bir xonadonda ichki va tashqi hovlilar mavjud bolib, hovlilarda tashkil qilinadigan maktablarda, asosan, dastlabki xat-savod orgatilgan." },
    { title: "Ota-onalar", data: "Har bir ota-ona farzandlarini yoshligidan talim olish uchun maktablarga yuborilgan." },
    { title: "Dastlabki kitoblar", data: "Oquvchilar dastlab Haftiyakni uni tugatganlaridan song 'Chor-kitob'ni oqishgan." },
    { title: "Moliyalashtirish", data: "Madrasalar va maktablar vaqf mulkidan moliyalashtirilgan." },
    { title: "Talabalar", data: "Talabalar madrasaga maktabni tugatganidan song qabul qilingan." },
    { title: "Yosh oralig‘i", data: "Ularning yoshi 10 yoshdan 40 yoshgacha bolgan." },
    { title: "XIX asrning boshlarida", data: "Britaniyaning Ost - Indiya kompaniyasi strategik ahamiyatga ega bolgan xonliklar hududiga qiziqa boshladi." },
    { title: "1825", data: "Angliya M. Murkroftni Buxoro amirligiga yuboradi." },
    { title: "1832", data: "Buxoroga A. Byorns yuborildi." },
    { title: "1843", data: "Xiva va Buxoroga kapitan J. Abbot yuborilgan." },
    { title: "1844", data: "Mayor I. Volf Buxoroga yuborildi." },
    { title: "1842", data: "Ch. Stoddart va A. Konnoli Buxoroga kelib, amir tomonidan qatl qilindi." },
    { title: "Afg‘oniston bilan sulh tuzilib", data: "Angliya hukumati Buxoroga qarshi qurollantiradi." },
    { title: "1855", data: "Ozbeklar va tojiklar yashaydigan Amudaryoning janubiy sohilidagi hududlar Afgoniston viloyatiga aylantirildi." },
    { title: "Britaniya qiziqishi", data: "Ost - Indiya kompaniyasi strategik ahamiyatga ega bolgan xonliklar hududiga qiziqa boshladi." },
    { title: "Buxoroga yuborish", data: "Angliya M. Murkroftni Buxoro amirligiga yuboradi." },
    { title: "Buxoro missiyasi", data: "Buxoroga A. Byorns yuborildi." },
    { title: "Kapitan yuborilishi", data: "Xiva va Buxoroga kapitan J. Abbot yuborilgan." },
    { title: "Mayor yuborilishi", data: "Mayor I. Volf Buxoroga yuborildi." },
    { title: "Buxorodagi voqea", data: "Ch. Stoddart va A. Konnoli Buxoroga kelib, amir tomonidan qatl qilindi." },
    { title: "Afg‘oniston bilan sulh", data: "Angliya hukumati Buxoroga qarshi qurollantiradi." },
    { title: "Afg‘oniston viloyati", data: "Ozbeklar va tojiklar yashaydigan Amudaryoning janubiy sohilidagi hududlar Afgoniston viloyatiga aylantirildi." },
    { title: "Harbiy harakatlar kuchayishi", data: "Rossiya imperatori Aleksandr II 1859-yilda Qoqon xonligini bosib olishning davom ettirilishi togrisida korsatma berdi." },
    { title: "Toshkentni bosib olish zaruriyati", data: "Toshkent shahri bosib olinishi zarur edi." },
    { title: "Oqmachit qal'asi", data: "Oqmachit qalasi Toshkentni bosib olishda harbiy harakatlarning tayanchi boldi." },
    { title: "Birinchi hujum", data: "Imperiya qoshinlarining Oqmachit qalasini bosib olishdagi dastlabki harakatlari (1852-yil) maglubiyatga uchradi." },
    { title: "Ikkinchi hujum", data: "1853-yilda Oqmachit qalasini egalash uchun ikkinchi marta hujum boshlandi." },
    { title: "Qal'a himoyachilarining qarshiligi", data: "3 mingdan ortiq rus harbiy qoshiniga 400 kishidan iborat qala himoyachilari 20 kun davomida qarshilik korsatdi." },
    { title: "Oxirgi jang", data: "Qurshovda qolgan qala himoyachilari oxirgi imkoniyatlari qolgunicha jang qildilar." },
    { title: "Qal'aning egallanishi", data: "Rossiya imperiyasi qoshinlari tomonidan qala egallandi va bu qalaga Perovskiy forti deb nom berildi." },
    { title: "Qo‘shinlar Tashkiliy harakati", data: "1864-yilda Rossiya imperiyasining uch mingdan koproq qoshini Toshkentni bosib olish uchun ikki yonalishda yolga chiqdi." },
    { title: "Perovskiy forti orqali harakat", data: "Birinchi yonalish Perovskiy fortidan (Orenburg tomondan) boldi." },
    { title: "Ver­niy shahri orqali harakat", data: "Ikkinchi yonalish Verniy (Almati) shahri tomondan boldi." },
    { title: "Avliyoota (Taroz) bosib olinishi", data: "Ular avval Talas daryosining chap sohilidagi Avliyoota (hozirgi Taroz shahri)ni bosib oldi." },
    { title: "Mudofaa tayyorgarligi", data: "Turkiston va Chimkent shahrlari mudofasiga Qoqon xonining amirlar shahridagi Aliquli rahbarlik qildi." },
    { title: "Qo‘shinlarning qurollanishi", data: "Osha davrning zamonaviy qurollari bilan qurollangan imperiya qoshinlari Turkiston shahrini ishgol qildi." },
    { title: "Toshkentga hujum tayyorgarligi", data: "Imperiya qoshinlari 20 kilometrlik qala devori bilan oralgan Toshkentni bosib olishga tayyorgarlik kora boshladi." },
    { title: "M. Chernyayevning tayinlanishi", data: "Bu harbiy harakatlarga M. Chernyayev qomondon etib tayinlandi." },
    { title: "Chimkentning egallanishi", data: "1864-yil kuzida Chimkent shahri egallanib, Yangi Qoqon chizigi asosida qolga kiritilgan qalalar birlashtirildi." },
    { title: "Istehkom chizig‘ining shakllanishi", data: "Natijada Raim qalasidan Perovskiy fortigacha Sirdaryo istehkom chizigi, Semipalatinskdan Verniy shahrigacha Sibir istehkom chizigi vujudga keldi." },
    { title: "Toshkentning ahamiyati", data: "Toshkent Orta Osiyoning siyosiy, iqtisodiy, yirik mamuriy va savdo-sotiq markazlaridan biri hisoblangan." },
    { title: "Darvozalar va mudofaa", data: "Har tomondan shaharga kirish uchun qurilgan 12 ta darvozalari soqchilar tomonidan qoriqlangan." },
    { title: "Mudofaa devori va xandaqlar", data: "Shaharni mudofaa qilish uchun qurilgan devor ortida Kaykovus arigining suvi bilan toldiriladigan xandaqlar bolgan." },
    { title: "M. Chernyayevning hujumi", data: "1864-yil 1-oktyabrida M. Chernyayev Toshkentni bosib olmoqchi boldi." },
    { title: "Himoyachilarning qarshiligi", data: "Shahar himoyachilari Chernyayevni Chimkentga chekinishga majbur qildi." },
    { title: "Toshkent darvozalari", data: "XIX asrning ikkinchi yarmida Toshkent shahrining 12 ta darvozasi bolgan." },
    { title: "Darvozalar ro‘yxati", data: "Bular: Labzak, Taxtapul, Qorasaroy, Sagbon, Chigatoy, Kokcha, Samarqand, Kamolon, Beshyogoch, Qoymas, Qoqon, Qoshgar." },
    { title: "Toshkent dahalari", data: "Toshkent tortta dahalarga bolinib, har bir daha oz oqsoqoli tomonidan boshqarilgan." },
    { title: "Niyozbek qal’asining topshirilishi", data: "1865-yil aprel oxirida M. Chernyayev boshchiligidagi harbiy qoshin Niyozbek qalasiga jangsiz topshirishni taklif qiladi, lekin qala himoyachilari rad javobini berib, mudofaaga otadi." },
    { title: "Niyozbek qal’asining bosilishi", data: "Qala toplardan oqqa tutilib, devorlari buzilib, dushman qoliga otdi." },
    { title: "Toshkentni suv ta’minotidan uzish", data: "Niyozbek qalasining bosib olinishi Chernyayevga Toshkentni suv taminotidan uzib qoyish imkonini berdi." },
    { title: "Chirchiq daryosidagi to‘g‘on", data: "Ushbu buyruq bilan Toshkent shahri aholisini suv bilan taminlaydigan Chirchiq daryosidagi togon buzib tashlandi." },
    { title: "Toshkentning strategik ahamiyati", data: "Toshkent Orta Osiyoni bosib olish uchun asosiy yolak va harbiy qoshinlar uchun tayanch nuqta vazifasini bajara oladigan joy hisoblangan." },
    { title: "Toshkentning mudofasi", data: "Toshkent shahri suvsiz qolgan bolsa-da, sarbozlar va aholi qattiq qarshilik korsatdi, imperiya qoshinlari tortta top himoyasida bolgan tosiqdan ota olmadilar." },
    { title: "Aliqulining halok bo‘lishi", data: "Toshkent himoyasida Aliquli boshchiligidagi qoshinlar qarshilik korsatdilar, lekin uning halok bolishi shahar himoyachilarini sarsimaga solib qoydi." },
    { title: "Buxoro amirligidan kelgan qo‘shinlar", data: "Buxoro amirligidan kechikib yetib kelgan qoshinlar shahar himoyasiga foyda keltira olmadi." },
    { title: "Toshkentning egallanishi", data: "1865-yil iyunda Toshkent shahar imperiya qoshinlari tomonidan egallandi." },
    { title: "Oqsoqollar bilan muzokaralar", data: "M. Chernyayev Beshyogoch, Kokcha, Sebzor va Shayxontohur dahalarining oqsoqollarini chaqirib, shaharni ixtiyoriy ravishda topshirish togrisidagi sulhni imzolashga majbur qildi." },
    { title: "Surgun qilingan shaxslar", data: "Bunga qarshi bolgan Solihbek dodxoh, Abulqosim eshon va Hakimxoja Sibirga surgun qilindi." },
    { title: "Turkiston viloyatining tuzilishi", data: "Harbiy istilochilik yurishlari natijasida bosib olingan hududlarda Turkiston viloyati tuzilib, M. Chernyayev gubernator qilib tayinlandi." },
    { title: "Toshkentning tayanch ma’muriy hudud vazifasi", data: "Viloyat bolimlarining harbiy asosda tashkil qilinishi imperiya hukumatining kelgusidagi harbiy rejalarini amalga oshirishida Toshkentning tayanch mamuriy hudud vazifasini otashi kozda tutilgan edi." },
    { title: "Oqsoqollarni ixtiyoriy ravishda taslim bo'lishi", data: "Chernyayev xalqaro doirada bosqinchilik xatti-harakatlarini oqlash maqsadida mahalliy oqsoqollarni Toshkent ixtiyoriy ravishda taslim boldi, toshkentliklarning ozlari aholi tinchligini saqlab qolish maqsadida Rossiya askarlariga shahar darvozalarini ochib berdilar, degan mazmundagi xatni imperator nomiga yozishga majburladi." },
    { title: "Turkiston viloyatining tashkil topishi", data: "1865-yilda Turkiston viloyati tashkil qilindi. 1867-yilda bosib olingan hududlarni oz ichiga oluvchi Turkiston general-gubernatorligi tashkil qilindi va Turkiston harbiy okrugi tuzildi." },
    { title: "Toshkentning markaz sifatida belgilanishi", data: "Toshkent shahri general-gubernatorlikning markazi qilib belgilandi. Rossiya imperatori farmoniga kora Turkiston general-gubernatorligiga general fon Kaufman tayinlandi." },
    { title: "Viloyatlar tarkibi", data: "Turkiston general-gubernatorligi dastlab mamuriy jihatdan Sirdaryo (markazi - Toshkent) va Yettisuv (markazi - Verniy) viloyatlariga bolingan." },
    { title: "Sirdaryo viloyatining hududi", data: "Sirdaryo viloyatining hududiga 1865-yilda tashkil qilingan Turkiston viloyatiga tegishli bolgan yerlar va Qoqon xonligining bosib olingan shimoliy hududlari kirgan." },
    { title: "Yettisuv viloyatining tashkil topishi", data: "Yettisuv viloyati esa Semipalatinsk viloyatining Sergiopol, Kopal va Olatavsk okrugi yerlaridan iborat holda tashkil qilindi." },
    { title: "Rossiya imperiyasining O‘rta Osiyodagi harakatlari kuchaydi", data: "Aleksandr II Qoqon xonligini bosib olishni buyurdi." },
    { title: "Toshkentning harbiy ahamiyati", data: "Oqmachit qalasi harbiy harakatlarning tayanchiga aylandi." },
    { title: "Niyozbek qal’asining bosilishi", data: "Chernyayev Niyozbek qalasini egallab, Toshkentni suv taminotidan uzdi." },
    { title: "Toshkent shahrining mudofasi", data: "Shahar himoyachilari kuchli qarshilik korsatdilar, ammo 1865-yilga kelib shahar bosib olindi." },
    { title: "Toshkentning ixtiyoriy topshirilishi", data: "Oqsoqollar shaharni topshirishga majbur boldilar." },
    { title: "Turkiston viloyati tashkil qilindi", data: "1865-yilda Turkiston viloyati, 1867-yilda esa Turkiston general-gubernatorligi tuzildi." },
    { title: "Orenburg general-gubernatorligi", data: "Orta Osiyodan uzoqda joylashgani sababli alohida general-gubernatorlik tashkil etilishi talab etildi." },
    { title: "Rossiya imperiyasi Toshkentni bosib oldi", data: "Barcha harbiy harakatlar Toshkentdan boshqarila boshlandi." },
    { title: "Mustamlakachilarning tamoyili", data: "Bolib tashla va hukmronlik qil tamoyiliga asoslanib, xonliklarni birlashishiga yol qoymadi." },
    { title: "Yerjar qishlog‘idagi to‘qnashuv", data: "1866-yil 8-mayda Rossiya imperiyasi va Buxoro amirligi qoshinlari toqnashdi." },
    { title: "Buxoro qo‘shinlarining mag‘lubiyati", data: "Kuchlar teng bolmagani uchun amir qoshinlari maglubiyatga uchradi." },
    { title: "Xo‘jand qal’asining qamal qilinishi", data: "May oyida Xojand qalasi ikki kun davomida qamal qilindi va shahar egallandi." },
    { title: "Buxoro amiri bilan sulh shartnomasi", data: "Rossiya imperiyasining Turkiston viloyati gubernatori N. Krijanovskiy 10 kun mobaynida 100 ming rubl tovon tolashni talab qildi." },
    { title: "Buxoro amirligi ustiga hujum", data: "Muddat otgach, Krijanovskiy Buxoro amiri talablarni bajarmaganligi uchun hujum boshlashga buyruq berdi." },
    { title: "O‘ratepa va Jizzaxning egallanishi", data: "Gubernatorning harbiy qoshinlari Oratepani egallab, Jizzaxga qarshi harakat boshladi." },
    { title: "Jizzax jangida halok bo‘lganlar", data: "Bu jangda har ikkala tomondan 6 mingdan koproq kishi halok boldi." },
    { title: "Sirdaryo viloyatining tashkil qilinishi", data: "1864 - 1866-yillar davomida bosib olingan hududlarni oz ichiga olgan Sirdaryo viloyati tashkil qilindi." },
    { title: "Samarqandga bostirib kirish", data: "1868-yilda Turkiston general-gubernatori Kaufman amir Muzaffarni bostirib kirishda ayblab, Samarqandga harbiy otryad bilan bostirib kirdi." },
    { title: "Samarqand jangida mag‘lubiyat", data: "Buxoro amiri qoshini Choponota va Zirabuloq tepaligida maglubiyatga uchradi." },
    { title: "Kaufman tomonidan sulh taklifi", data: "Kaufman Samarqandni Rossiyaga berish, harbiy xarajatlarni tolash va Turkiston olkasida qolga kiritilgan barcha narsalarni Rossiya mulki deb etirof etishni taklif qildi." },
    { title: "Samarqandda kurash", data: "Kitob begi Jorabek va Shahrisabz begi Bobobek Samarqandda kurash olib bordi." },
    { title: "Samarqandga hujum", data: "1868-yil 2-iyunda mudofaachilar Rossiya imperiyasi qoshinlari garnizoni joylashgan qalaga hujum qilishdi." },
    { title: "Rossiya imperiyasining harbiy harakatlari", data: "Rossiya imperatori Aleksandr II ning korsatmasi bilan Toshkentni bosib olish jarayoni kuchaydi." },
    { title: "Niyozbek qal’asining bosilishi", data: "M. Chernyayev boshchiligidagi qoshin Niyozbek qalasini bosib olib, Toshkentni suv taminotidan uzdi." },
    { title: "Toshkent shahridagi mudofaa", data: "Shahar himoyachilari Rossiya imperiyasiga qarshi qattiq qarshilik korsatdilar." },
    { title: "Xalqaro shartnomalar", data: "Rossiya imperiyasi Buxoro amirligi bilan sulh shartnomasini imzolashga majbur boldi." },
    { title: "Zirabuloq shartnomasi", data: "Amir Muzaffar Rossiya imperiyasining yangi chegaralarini qabul qilib, bu shartnoma tuzildi." },
    { title: "Buxoro amirligi va Rossiya imperiyasi", data: "Rossiya imperiyasi Buxoro amirligini oz tasir doirasiga olib, vakil tayinladi." },
    { title: "Zirabuloq shartnomasi", data: "Shartnomaga kora, Toshkentdan Samarqandgacha bolgan barcha bosib olingan hududlar, jumladan Xojand, Oratepa, Panjikent, Jizzax, Samarqand va Kattaqorgon shaharlari Rossiya imperiyasiga otdi." },
    { title: "Chegaralarni belgilash muzokaralari", data: "1869-1870-yillarda Rossiya imperiyasi Angliya bilan Afgoniston va Orta Osiyodagi chegaralarni belgilash boyicha muzokaralar olib bordi. Natijada Amudaryo boylab Panj tumanidan otkazilishi kelishildi. 1881-yilda Buxoro amirligi va Eron ortasidagi chegara maxfiy shartnoma bilan belgilandi. 1885-1887-yillarda ingliz-rus komissiyasi Afgoniston va Buxoro amirligi ortasidagi chegara chizigini belgilashni yakunladi." },
    { title: "Xiva xonligini bosib olish harakatlari", data: "Rossiya imperiyasi keyingi harakatlarini Xiva xonligini bosib olishga qaratdi, bu orqali Amudaryo ustidan nazoratni qolga kiritishni maqsad qilib oldi." },
    { title: "Tayyorgarlik jarayoni", data: "Rossiya imperiyasi besh yil davomida Xiva xonligiga qarshi puxta tayyorgarlik kordi." },
    { title: "Harbiy qo‘shinlarning yo‘lga chiqishi", data: "Kaufman boshchiligidagi kop sonli harbiy qoshin 1873-yil fevralda garbda Mangishloq, shimolda Orenburg, sharqda Turkiston va janubda Krasnovodskdan yolga chiqdi." },
    { title: "Janglar va to‘qnashuvlar", data: "Rossiya imperiyasi qoshinlari bilan Xiva xonligi qoshinlari ortasida may oyida Hazorasp qalasi, Qongirot, Xojayli, Mangit shaharlari va Xiva yaqinida janglar bolib otdi." },
    { title: "Kaufman qo‘shinlarining Xivaga yetib kelishi", data: "1873-yil may oyining ortalarida mustamlakachi hukumatning asosiy qoshinlari Xivaga yetib keldi." },
    { title: "Xivani egallash", data: "Kaufman qoshinlari Hazorasp darvozasi orqali xonlik poytaxtini egalladi." },
    { title: "Xon xazinasining musodara qilinishi", data: "Kaufman Xivani bosib olgandan song xon xazinasini kontributsiya evaziga musodara qilib, moddiy va manaviy boyliklarni Sankt-Peterburgga jonatdi." },
    { title: "Gandimiyon shartnomasi", data: "1873-yil 12-avgustda Xiva xoni Muhammad Rahimxon II Gandimiyon qishlogida shartnoma imzolashga majbur boldi." },
    { title: "Xiva xonligi va Amudaryo", data: "Xiva xonligiga qarashli Amudaryoning ong sohili va qoshni yerlarning barchasi xonlik tasarrufidan chiqdi." },
    { title: "Tovon miqdori", data: "Shartnomaga binoan Xiva xonligi 2 million 200 ming rubl miqdoridagi tovonni 20 yil davomida tolashi belgilandi." },
    { title: "Tovonning aholidan yig‘ilishi", data: "Xonlik xazinasida yetarli pul bolmaganligi uchun tovon aholidan yigib olinadigan boldi." },
    { title: "Xiva xonligining tobeligi", data: "Gandimiyon shartnomasi Xiva xonligining Rossiya imperiyasiga tobeligi va xonning boshqa davlatga boysunishi haqida hujjat boldi." },
    { title: "Xiva xonligiga 1717-yildagi hujum", data: "1717-yilda A. Bekovich-Cherkasskiy boshchiligidagi qoshinlarning Xiva xonligiga hujumi muvaffaqiyatsiz tugadi." },
    { title: "Xiva xonligiga 1839-yildagi hujum", data: "1839-yilda V. Perovskiy boshchiligidagi qoshinlarning Xiva xonligiga hujumi ham muvaffaqiyatsiz boldi." },
    { title: "Rossiya imperiyasining Qo‘qon xonligiga hujumlari", data: "XIX asrning 50 - 60-yillarida Rossiya imperiyasi Qoqon xonligi hududining bir qismini harbiy yol bilan bosib oldi." },
    { title: "Qo‘qon xonligidagi ichki nizolar", data: "Rossiya istilosidan keyin Qoqon xonligida ichki nizolar va xalq noroziligi kuchaydi, xonlik iqtisodiy qiyinchiliklarga duch keldi." },
    { title: "Xudoyorxonning vafoti", data: "Xonlikdagi nizolarni bartaraf eta olmagan Xudoyorxon haj ziyoratiga ketib, Afgonistonda vafot etdi." },
    { title: "Nasriddinbekning taxtga chiqishi", data: "1875-yilda Nasriddinbek taxtga chiqdi, lekin xonlikdagi siyosiy vaziyat yanada keskinlashib, qozgolonlar boshlandi." },
    { title: "Qo‘qonning taslim bo‘lishi", data: "1875-yil 22-sentyabrda Nasriddinbek Kaufman bilan taslim bolganlik haqidagi shartnomani imzoladi." },
    { title: "Po‘latxon qo‘zg‘oloni", data: "Nasriddinbek imzolagan shartnomadan norozi bolgan aholi Polatxon boshchiligida qozgolon kotardi." },
    { title: "Qo‘qon xonligining tugatilishi", data: "1876-yil fevral oyida Polatxon qatl qilinib, Qoqon xonligi tugatildi va Fargona viloyati tashkil qilindi." },
    { title: "Po‘latxon qo‘zg‘oloni", data: "Polatxon asli ismi Ishoq Hasan ogli bolib, Qoqon xoni Olimxon (1801 - 1810) nabirasi edi. U 18731876-yillarda soxta xon sifatida qozgolonga rahbarlik qilgan." },
    { title: "Rossiya imperiyasining O‘rta Osiyoni bosib olishi", data: "Orta Osiyo Rossiya imperiyasi tomonidan tort bosqichda bosib olindi. Birinchi bosqich (1847 - 1865)da Qoqon xonligining shimoli-garbiy viloyatlari va Toshkent shahri istilo qilindi. Ikkinchi bosqich (1865 - 1868)da Qoqon xonligi va Buxoro amirligiga qarshi harbiy harakatlar amalga oshirildi. Uchinchi bosqich (1873 - 1879)da Xiva xonligining bir qismi va Qoqon xonligining toliq yerlari bosib olindi. Tortinchi bosqich (1880 - 1885)da turkmanlar boysundirildi." },
    { title: "Turkiston general-gubernatorligining ma’muriy-hududiy tuzilishi", data: "Turkiston general-gubernatorligi vassallar sifatida Buxoro amirligi va Xiva xonligini oz ichiga olgan. Sirdaryo viloyatiga Gazali, Perovskiy, Chimkent, Avliyoota, Toshkent kirgan. Yettisuv viloyatiga Verniy, Jarkent, Kopal, Lepsinek, Prjevalsk uezdlari kirgan. Fargona viloyatiga Margilon, Andijon, Qoqon, Namangan, Osh uezdlari va Pomir kirgan. Samarqand viloyatiga Samarqand, Kattaqorgon, Jizzax va Xojand uezdlari kirgan. Kaspiyorti viloyatiga Ashxobod, Krasnovodsk, Mangishloq, Marv va Tajan uezdlari kirgan." },
    // TURKISTON O‘LKASIDA SIYOSIYMA’MURIY BOSHQARUV TIZIM   shu mavzudan davom etiladi...
]

module.exports = {
    users,
    informations,
}
